services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"   # HTTP
      - "6334:6334"   # gRPC
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:6333"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  qdrant_storage: